CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

sudoku.exe:
	$(CC) $(CFLAGS) -o sudoku.exe sudoku.c
	./sudoku.exe

mandelbrot.exe:
	$(CC) $(CFLAGS) -o mandelbrot.exe mandelbrot.c -lm
	./mandelbrot.exe

mandelbrot2.exe:
	$(CC) $(CFLAGS) -o mandelbrot2.exe mandelbrot2.c -lm
	./mandelbrot2.exe