CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

white.exe:
	$(CC) $(CFLAGS) -o white.exe white.c
	./white.exe

plotting.exe:
	$(CC) $(CFLAGS) -o plotting.exe plotting.c
	./plotting.exe

plotting2.exe:
	$(CC) $(CFLAGS) -o plotting2.exe plotting2.c -lm
	./plotting2.exe
