CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

blatt03_3a.exe:
	$(CC) $(CFLAGS) -o blatt03_3a.exe blatt03_3a.c
	./blatt03_3a.exe

blatt03_3b.exe:
	$(CC) $(CFLAGS) -o blatt03_3b.exe blatt03_3b.c
	./blatt03_3b.exe

blatt03_2.exe:
	$(CC) $(CFLAGS) -o blatt03_2.exe blatt03_2.c