CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

white.exe:
	$(CC) $(CFLAGS) -o white.exe white.c
	./white.exe

plotting.exe:
	$(CC) $(CFLAGS) -o plotting.exe plotting.c -lm
	./plotting.exe

math.exe:
	$(CC) $(CFLAGS) -o math.exe math.c
	./math.exe
	
	